#!/bin/sh
exec 2>&1
#sed "s/HOSTNAME/$HOSTNAME/" /etc/confd/templates/bird.toml.template > /etc/confd/conf.d/bird.toml
ETCD_NODE=${ETCD_ENDPOINTS:=${ETCD_SCHEME:=http}://${ETCD_AUTHORITY}}
ETCD_ENDPOINTS_CONFD=`echo "-node=$ETCD_NODE" | sed -e 's/,/ -node=/'`

exec confd -confdir=/etc/confd -interval=5 -watch --log-level=debug \
           $ETCD_ENDPOINTS_CONFD -client-key=${ETCD_KEY_FILE} \
           -client-cert=${ETCD_CERT_FILE} -client-ca-keys=${ETCD_CA_CERT_FILE}
